### ISSUE TITLE
There are no labels in the csv file

### ISSUE THREAD

**Issue by hytryboyk** [UESTC-nnLab/ProDiv#1]
I also couldn't find the label information in the official website

**Comment by liupei101** [comment]
Thx for your interest. Please refer to [the commit](https://github.com/UESTC-nnLab/ProDiv/commit/36ea9452487984c6e806d39afe946c07a64d5178).

**Comment by hytryboyk** [comment]
Thank you for your reply，but there are only part of the labels, could you provide all the complete labels?
